[profile.default]
solc_version = "0.8.19"
src = "contracts"
script = "script"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
ETHERERUM      = "${RPC_URL_ETHERERUM}"
